### ISSUE TITLE
It don't work no more

### ISSUE THREAD

**Issue by samuelbennett** [chewett/what_is_the_date#6]
I don't the date. Halp!11!!!!11

Please do the needful

**Comment by chewett** [comment]
As you can see from the clear commit message i haz halped you https://github.com/chewett/what_is_the_date/commit/55cbed39631347b29b97e8a5e6c50184c9cc69f7

**Comment by samuelbennett** [comment]
Thanks for the halp. Please don't break it again, I have replaced the sun with this repo as my authoritative source.
